<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN15I51216GR512" failures="4" tests="7" name="Surefire test" time="93.797" errors="0" timestamp="2025-02-17T04:51:22 IST">
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.389">
    <failure type="java.lang.AssertionError" message="Log in failed expected [Log in successful.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: Log in failed expected [Log in successful.] but found [User does not exist.]
at nnd.Pages.DB_LoginPage.loginAlertHandle(DB_LoginPage.java:115)
at nnd.TestCases.DB_LoginTest.inValidUserLogin(DB_LoginTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- inValidUserLogin -->
  <testcase classname="nnd.TestCases.DB_LoginTest" name="inValidUserLogin" time="8.41">
    <failure type="java.lang.AssertionError" message="Log in failed expected [Log in successful.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: Log in failed expected [Log in successful.] but found [User does not exist.]
at nnd.Pages.DB_LoginPage.loginAlertHandle(DB_LoginPage.java:115)
at nnd.TestCases.DB_LoginTest.inValidUserLogin(DB_LoginTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- inValidUserLogin -->
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.429"/>
  <testcase classname="nnd.TestCases.DB_LoginTest" name="validUserLogin" time="5.415"/>
  <testcase classname="nnd.TestCases.DB_HomeTest" name="verifyPurchaseItem" time="9.048"/>
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="11.63">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
  <testcase classname="nnd.TestCases.DB_RegisterTest" name="validUserSignUp" time="10.39">
    <failure type="java.lang.AssertionError" message="Signup failed expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: Signup failed expected [Sign up successful.] but found [This user already exist.]
at nnd.Pages.DB_RegisterPage.clickSignUp(DB_RegisterPage.java:67)
at nnd.TestCases.DB_RegisterTest.validUserSignUp(DB_RegisterTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validUserSignUp -->
</testsuite> <!-- Surefire test -->
